---
abstract: 'SeeAlso handling of PND Numbers (Personennormdatei)'
author:
  - 'Thomas Berger C<< <THB@gymel.com> >>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SeeAlso-Identifier-PND
provides:
  SeeAlso::Identifier::PND:
    file: lib/SeeAlso/Identifier/PND.pm
    version: 0.61
requires:
  SeeAlso::Identifier: 0.46
  SeeAlso::Identifier::GND: 0.54
  perl: v5.8.2
resources:
  license: http://dev.perl.org/licenses/
version: 0.61
